### ISSUE TITLE
Parking a vehicle causes it to spawn multiple times

### ISSUE THREAD

**Issue by IanToujou** [MaDHouSe79/qb-parkinglite#4]
## General information

When using the park command to park the vehicle, my character climbs out of the car and everything works fine, until the car with the parked state spawns.

The parked car has all the information displayed above it, but 2 or even more cars spawn on top of it.

![issue](https://user-images.githubusercontent.com/44029196/186782732-02f86b80-5fd9-40a0-8eb0-99be77d9318a.png)

Also, getting back inside the car and starting it is no problem. The database and all the stored data is also fine, I could not find any duplicate entries or other problems.

The same issue with multiple cars also occurs when I restart the script. However, starting the server from scratch with parked cars in the database seems fine and the cars are parked without any duplicates.

## Attempting to fix it

I tried to debug the issue by looking into the script, but I am clueless at the moment. I just wanted to report this in case other users have the same issue, maybe someone can find a fix.

**Comment by MaDHouSe79** [comment]
Thanks for your message, if you join my discord I can give you another parkinglite I'm currently working on to fix this issue. 
you can test it if you want. cause this only happens when you have more people on the server, and i changes some code, so instead to check every time, now i use a onjoin method and i hope this wil fix that issue. but you have to test it out if this works, cause if this is working than this is also the fix for the normal parking script ;)
